const ACTIONS = {
    SHOW_GOALS: "SHOW_GOALS",
    SET_CURRENT_GOAL: "SET_CURRENT_GOAL",
    CREATE_GOAL: "CREATE_GOAL",
    SUBMIT_GOAL: "SUBMIT_GOAL",
    MOVE_GOAL_TO_MONTH: "MOVE_GOAL_TO_MONTH"
}

export default ACTIONS;